# Generated by Django 3.2.8 on 2021-12-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='set',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evidence',
            name='set',
            field=models.IntegerField(default=1),
        ),
    ]
