# Generated by Django 3.2.8 on 2021-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='es_id',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
