# Generated by Django 3.2.8 on 2021-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_es_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='b1',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='project',
            name='k',
            field=models.FloatField(default=0.75),
        ),
    ]
