# Generated by Django 3.2.8 on 2021-12-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211223_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.document'),
        ),
    ]
